### ISSUE TITLE
Failing to create new Storage

### ISSUE THREAD

**Issue by durnerj** [Breee/STOMACH#6]
Can't create new Storage, error is this:

NoReverseMatch at /storage/new/

Reverse for 'storage_detail' with arguments '('',)' not found. 1 pattern(s) tried: ['storage/(?P<storage_id>[0-9]+)$']

**Comment by Breee** [comment]
Yes, storage_new:

Also pass the id of the New storage as Part of the context

Am 08.06.2017 1:08 nachm. schrieb "durnerj" <notifications@github.com>:

**Comment by Breee** [comment]
Anyway,  storage_new and storage_edit can be merged Into one function at some point

**Comment by Breee** [comment]
fixed by 8291f5b
